//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AviaTicketsWpfApplication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AviaTicketsWpfApplication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adults.
        /// </summary>
        public static string Adults {
            get {
                return ResourceManager.GetString("Adults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airline with such the code or name not found..
        /// </summary>
        public static string AirlineNotFound {
            get {
                return ResourceManager.GetString("AirlineNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airlines.
        /// </summary>
        public static string Airlines {
            get {
                return ResourceManager.GetString("Airlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airlines alliances.
        /// </summary>
        public static string AirlinesAlliances {
            get {
                return ResourceManager.GetString("AirlinesAlliances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airports.
        /// </summary>
        public static string Airports {
            get {
                return ResourceManager.GetString("Airports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar of prices by month.
        /// </summary>
        public static string CalendarTickets {
            get {
                return ResourceManager.GetString("CalendarTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheapest tickets.
        /// </summary>
        public static string CheapestTickets {
            get {
                return ResourceManager.GetString("CheapestTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        public static string Children {
            get {
                return ResourceManager.GetString("Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose airline:.
        /// </summary>
        public static string ChooseAirline {
            get {
                return ResourceManager.GetString("ChooseAirline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose city:.
        /// </summary>
        public static string ChooseСity {
            get {
                return ResourceManager.GetString("ChooseСity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City with such the code or name not found..
        /// </summary>
        public static string CityNotFound {
            get {
                return ResourceManager.GetString("CityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading... Wait..
        /// </summary>
        public static string DataLoading {
            get {
                return ResourceManager.GetString("DataLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depart date.
        /// </summary>
        public static string DepartDateName {
            get {
                return ResourceManager.GetString("DepartDateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City of arrival.
        /// </summary>
        public static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct flights.
        /// </summary>
        public static string DirectFlights {
            get {
                return ResourceManager.GetString("DirectFlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The duration of leave: {0} - {1} days.
        /// </summary>
        public static string DurationLeave {
            get {
                return ResourceManager.GetString("DurationLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 404.
        /// </summary>
        public static string Error404 {
            get {
                return ResourceManager.GetString("Error404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in parameters..
        /// </summary>
        public static string ErrorParams {
            get {
                return ResourceManager.GetString("ErrorParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controlled duplicates {0}. It is not possible to show information..
        /// </summary>
        public static string FormatControlledDuplicates {
            get {
                return ResourceManager.GetString("FormatControlledDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading... {0}% ({1}).
        /// </summary>
        public static string FormatLoadingLine {
            get {
                return ResourceManager.GetString("FormatLoadingLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can get token and marker.
        /// </summary>
        public static string GetToken {
            get {
                return ResourceManager.GetString("GetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string here {
            get {
                return ResourceManager.GetString("here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infants.
        /// </summary>
        public static string Infants {
            get {
                return ResourceManager.GetString("Infants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2015 Sample Travelpayouts API.
        /// </summary>
        public static string InfoStatusBar {
            get {
                return ResourceManager.GetString("InfoStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not data. Use search panel..
        /// </summary>
        public static string NotData {
            get {
                return ResourceManager.GetString("NotData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City of departure.
        /// </summary>
        public static string Original {
            get {
                return ResourceManager.GetString("Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page:.
        /// </summary>
        public static string PageNameStatusBar {
            get {
                return ResourceManager.GetString("PageNameStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planes.
        /// </summary>
        public static string Planes {
            get {
                return ResourceManager.GetString("Planes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular airline routes.
        /// </summary>
        public static string PopularAirlineRoutes {
            get {
                return ResourceManager.GetString("PopularAirlineRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular routes from city.
        /// </summary>
        public static string PopularRoutesFromCity {
            get {
                return ResourceManager.GetString("PopularRoutesFromCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prices.
        /// </summary>
        public static string Prices {
            get {
                return ResourceManager.GetString("Prices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to quit the application?.
        /// </summary>
        public static string QuestionExitApp {
            get {
                return ResourceManager.GetString("QuestionExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realtime search.
        /// </summary>
        public static string RealtimeTickets {
            get {
                return ResourceManager.GetString("RealtimeTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return date.
        /// </summary>
        public static string ReturnDateName {
            get {
                return ResourceManager.GetString("ReturnDateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routes.
        /// </summary>
        public static string Routes {
            get {
                return ResourceManager.GetString("Routes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved token.
        /// </summary>
        public static string SavedToken {
            get {
                return ResourceManager.GetString("SavedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates flights: {0:dd.MM.yyyy} - {1:dd.MM.yyyy}.
        /// </summary>
        public static string SpecialOfferFlightMessage {
            get {
                return ResourceManager.GetString("SpecialOfferFlightMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special offer on the airline site.
        /// </summary>
        public static string SpecialOfferLinkName {
            get {
                return ResourceManager.GetString("SpecialOfferLinkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special offers.
        /// </summary>
        public static string SpecialOffers {
            get {
                return ResourceManager.GetString("SpecialOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airline tickets on sale: {0:dd.MM.yyyy} - {1:dd.MM.yyyy}.
        /// </summary>
        public static string SpecialOfferSaleMessage {
            get {
                return ResourceManager.GetString("SpecialOfferSaleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application demonstrate some of the methods of the wrapper over.
        /// </summary>
        public static string TextAbout1 {
            get {
                return ResourceManager.GetString("TextAbout1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to which provides access to a cheap tickets from.
        /// </summary>
        public static string TextAbout2 {
            get {
                return ResourceManager.GetString("TextAbout2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application uses .
        /// </summary>
        public static string TextAbout3 {
            get {
                return ResourceManager.GetString("TextAbout3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrapper code for Travelpayouts API can be found on.
        /// </summary>
        public static string TextAboutEnd {
            get {
                return ResourceManager.GetString("TextAboutEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets.
        /// </summary>
        public static string Tickets {
            get {
                return ResourceManager.GetString("Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheapest tickets grouped by month.
        /// </summary>
        public static string TicketsGroupByMonth {
            get {
                return ResourceManager.GetString("TicketsGroupByMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        public static string TitleAbout {
            get {
                return ResourceManager.GetString("TitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close application.
        /// </summary>
        public static string TitleDlgExitApp {
            get {
                return ResourceManager.GetString("TitleDlgExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Tickets.
        /// </summary>
        public static string TitleFirstBlock {
            get {
                return ResourceManager.GetString("TitleFirstBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find tickets.
        /// </summary>
        public static string TitleSearchPanelButton {
            get {
                return ResourceManager.GetString("TitleSearchPanelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string TitleSecondBlock {
            get {
                return ResourceManager.GetString("TitleSecondBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show prices.
        /// </summary>
        public static string TitleShowPrices {
            get {
                return ResourceManager.GetString("TitleShowPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter token and marker for Travelpayouts API.
        /// </summary>
        public static string TitleTokenDlg {
            get {
                return ResourceManager.GetString("TitleTokenDlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows search panel.
        /// </summary>
        public static string TooltipSearchButton {
            get {
                return ResourceManager.GetString("TooltipSearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Class.
        /// </summary>
        public static string TripClass {
            get {
                return ResourceManager.GetString("TripClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buisness.
        /// </summary>
        public static string TripClassBuisness {
            get {
                return ResourceManager.GetString("TripClassBuisness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Econom.
        /// </summary>
        public static string TripClassEconom {
            get {
                return ResourceManager.GetString("TripClassEconom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use test token and marker.
        /// </summary>
        public static string UseTextToken {
            get {
                return ResourceManager.GetString("UseTextToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The adults can not be empty.
        /// </summary>
        public static string ValidateMsgAdults {
            get {
                return ResourceManager.GetString("ValidateMsgAdults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The children can not be empty.
        /// </summary>
        public static string ValidateMsgChildren {
            get {
                return ResourceManager.GetString("ValidateMsgChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The depart date can not be empty.
        /// </summary>
        public static string ValidateMsgDepartDate {
            get {
                return ResourceManager.GetString("ValidateMsgDepartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination can not be empty.
        /// </summary>
        public static string ValidateMsgDestination {
            get {
                return ResourceManager.GetString("ValidateMsgDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The infants can not be empty.
        /// </summary>
        public static string ValidateMsgInfants {
            get {
                return ResourceManager.GetString("ValidateMsgInfants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The marker can not be empty.
        /// </summary>
        public static string ValidateMsgMarker {
            get {
                return ResourceManager.GetString("ValidateMsgMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The origin can not be empty.
        /// </summary>
        public static string ValidateMsgOrigin {
            get {
                return ResourceManager.GetString("ValidateMsgOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The return date can not be empty.
        /// </summary>
        public static string ValidateMsgReturnDate {
            get {
                return ResourceManager.GetString("ValidateMsgReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token can not be empty.
        /// </summary>
        public static string ValidateMsgToken {
            get {
                return ResourceManager.GetString("ValidateMsgToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autocompletion.
        /// </summary>
        public static string WatermarkAutoTextBox {
            get {
                return ResourceManager.GetString("WatermarkAutoTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a date.
        /// </summary>
        public static string WatermarkDateTime {
            get {
                return ResourceManager.GetString("WatermarkDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter marker here.
        /// </summary>
        public static string WatermarkMarker {
            get {
                return ResourceManager.GetString("WatermarkMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter token here.
        /// </summary>
        public static string WatermarkToken {
            get {
                return ResourceManager.GetString("WatermarkToken", resourceCulture);
            }
        }
    }
}
